### ISSUE TITLE
allow configuration of the corner icon fill color

### ISSUE THREAD

**Issue by TheDiveO** [Koooooo-7/docsify-corner#4]
Thank you very much for your useful little helper! As my employer operates a huge Gitlab instance in-house I'm thankful for you having done already the work to use the proper repo system icon.

I noted that the Gitlab icon SVG path has a **fixed fill color** set. Depending on the theme color scheme set, this can be really hard on eyes, more so with petrol-like colors. This makes the corner icon stick out like a sore thumb. Can you please make the corner icon fill color configurable?

At the moment, I'm using a CSS fix that takes the current theme background color into account, so it relies on themeable. Maybe there's a better way to achieve this goal?

```css
.github-corner > svg > :nth-child(2) {
      fill: var(--base-background-color);
}
```
